### ISSUE TITLE
Latest release missing the option to show names ingame?

### ISSUE THREAD

**Issue by koreagunba** [ParadiseAigo/Tekken-7-Player-Displayer#16]
in the past there was an option to show names in game which was useful if playing on fullscreen and 1 monitor. i think the hotkey was ALT+S to activate it. 

also, when i press Open player list or Set tekken in window mode, my tekken instantly crashes.

**Comment by ParadiseAigo** [comment]
Yes, I removed the in-game display feature a few updates ago for various reasons, the biggest reason being that it simply no longer worked. I also thought that the in-game display wasn't needed because the program gave you the option to switch between full-screen and windowed, but since, like you said, that doesn't work either for you, I see how the program can become annoying to use.

As for opening the player list crashing your game: this is very weird to me, I have no idea how this is possible, but I'll check the code again later of course to be sure.

However, changing the window mode crashing your game is concerning. This is something that will happen if the addresses are not correct: in other words, the program is writing data in the wrong places.
Things that can cause this are:
-> Either your game is different then mine, because you are using other mods or programs that change the process which are causing my program to crash your game. (Cosmetic mods should be okay though I think.)
-> Or your version of Player-Displayer doesn't have the correct addresses because it is not the latest version.

Can you tell me if you are getting any errors in the black terminal/console thing, any error codes or error messages?

**Comment by Loemnk** [comment]
> in the past there was an option to show names in game which was useful if playing on fullscreen and 1 monitor. i think the hotkey was ALT+S to activate it.
> 
> also, when i press Open player list or Set tekken in window mode, my tekken instantly crashes.

Are you also running the Tekken Overlay?

If yes, that might be the reason. I had the same issue with the game crashing when running this and the Tekken Overlay at the same time trying to switch to Windowed Mode.

But since I use multiple displays this was never a problem for me.

**Comment by koreagunba** [comment]
@Loemnk Thank you, that was the cause of my problem. for some reason tekken overlay causes it to crash, but it functions properly otherwise.

@ParadiseAigo Also thanks for the in-depth response. It would be great to have the in-game display feature back in the future if its possible to fix. You are very kind!
