### ISSUE TITLE
Not recognizing existing ids

### ISSUE THREAD

**Issue by Erich0405** [ParadiseAigo/Tekken-7-Player-Displayer#19]
Hi, thanks for this program.

I have an issue where the program is not recognizing ids from the PlayerList, so i would write a comment on a player, the program says comment has been saved, i see id + comment is indeed saved on the PlayerList but the program keep saying Steam id NOT found in player list.

again thanks.

**Comment by ParadiseAigo** [comment]
Hi,

When the game is trying to match you with someone it is normal to get many id's of people you never played against before (that are not in the list), so the message itself is not really an error message.

Before giving the message "Steam id NOT found..." it prints a message "New Steam id found: 76561197960265729" which as you can see contains the steam id.

You should check the specific id's that it is telling you it is not finding in the list and see if they are actually in the list or not (open the list with Notepad or something). If they are though and it's giving you the "not found" message then there really is a problem. And in that case I am not sure what the cause of the problem could be, because reading from and writing to the file seems to be no problem since like you said the "saving a comment" feature works normally.

**Comment by Erich0405** [comment]
Steam ids and comments are saved in PlayerList, i checked it after writing comments, but the program seem to be having trouble reading the PlayerList and saying "Steam Id not found, no comments yet" as if ive never played with these players before.

Thanks for the reply, not a big issue, just thought i should let you know in case anyone else having this problem.

**Comment by Erich0405** [comment]
solved it, its because i copy pasted steam ids off the old player list to the new version, thats why.

is there any way to update player list from old version to the new one? if no then nevermind.

Thanks.

**Comment by ParadiseAigo** [comment]
Lists should work with any version of the program.

But maybe this can help: between every word in a line in the list there should be multiple tabs (those are the white spaces).

Line example in the list (with exactly 3 tabs in between each thing):
bigboss99			Hwoarang			(76561197960265730)			no comment yet

If you delete those tabs (or even if you randomely add spaces in between them) then the lines can no longer be read correctly.

**Comment by Erich0405** [comment]
ah yes, some of them have 1 space and 2 tabs instead of 3 tabs for some reason and i have over 1500 lines to check.

i will just start with a new player list, all good.

thanks very much for your help.
