### ISSUE TITLE
name dont shows up and keep crashing after

### ISSUE THREAD

**Issue by markhydra** [ParadiseAigo/Tekken-7-Player-Displayer#39]
so i got this issue somehow the name didnt show up anymore after the newest update and everytime u find someone the displayer keep crashing for me

**Comment by ParadiseAigo** [comment]
Can you clarify what you mean by "newest update"? Are you referring to the latest Tekken 7 5.10 update or are you talking about a specific Player-Displayer version. In any case I hope you are using the latest version of Player-Displayer (because this will make it easier for me to find the problem and fix it).

**Comment by markhydra** [comment]
> Can you clarify what you mean by "newest update"? Are you referring to the latest Tekken 7 5.10 update or are you talking about a specific Player-Displayer version. In any case I hope you are using the latest version of Player-Displayer (because this will make it easier for me to find the problem and fix it).

yep i mean the newest update and i tried the newest and the older one and it still crashes for me

**Comment by ParadiseAigo** [comment]
Can you test out this version for me?

https://github.com/ParadiseAigo/Tekken-7-Player-Displayer/releases/tag/v1.3.8

Don't try any of the extra features that require you to press ALT+whatever (switching window-mode, display in-game, etc.) because they won't work. But you should be able to see your opponent's name.
